### ISSUE TITLE
First test run

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/cgweb#1]
# Remarks (without suggestion for improvements)
- [x] The menu appearing on the right after you selected the customer should have a title denoting what you can do with it.
- [x] Same for the box that contains "Sample name", let's call it the info box. Why is it there? A simply 'Info' could be sufficient to denote that this is non-editable information.
- [x] Now the menu appears and I'm like: "Am I supposed to do something with this?" Answer: no, first fill in the form. "But it appeared and grabbed my attention, surely I have to do something with it now, right?" Nope, now please fill in the not colorful form instead.
- [x] I thought the X next to the priority was to remove the priority. I clicked it, removing the family instead. :(
- [ ] It is confusing that you have information on the left and right side. The function of the right side only becomes clearer when you submit multiple families. I would still like the info box to be as a tab that connects visually to the left side to denote that the right just provides somekind of summary about the info on the left.
- [x] The reset form button is .. dangerous. Two step reset would make my heart more at peace.
- [x] I'm always confused when a form needs to be filled in from top to bottom and the final action is something you need to click on top. The final action should be in the direction you were going when you were filling in the form.
- [ ] The sample part of the form resets when I first fill in the sample and then change my mind and go from fastq -> scout as Type.

**Comment by robinandeer** [comment]
> The menu appearing on the right after you selected the customer should have a title denoting what you can do with it.

What menu are you referring to? Maybe include a screenshot? @ingkebil
