### ISSUE TITLE
Required apptag when adding existing sample

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/cgweb#10]
Adding an existing sample to a family with externally sequenced samples requires the apptag to be filled in on the existing sample. But the app tag can't be filled in (and should not be filled in)

**Comment by emiliaol** [comment]
Only seem to happen when the original sample is sequenced at CG, if the original sample is also a previous external sample it works fine

**Comment by emiliaol** [comment]
Fun fact. If you select the existing family but delete the sample with the "wrong" apptag from the submission the sample will still be connected to the same family ID but obviously without the relation information.

**Comment by ingkebil** [comment]
Do you know if this bug still persists?

**Comment by patrikgrenfeldt** [comment]
resolved by #83
