### ISSUE TITLE
Make "Reference genome" field more stringent

### ISSUE THREAD

**Issue by sylvinite** [Clinical-Genomics/cgweb#153]
Customers are allowed to assign their own reference genome for their microbial sample.
Earlier we had an issue where a customer input " NC_016845.1" (notice the space).
This broke a few things downstream, which currently have been resolved.

More generally it would be good if this type of erroneously written reference genome was either cleaned up, or disallowed.

**Comment by patrikgrenfeldt** [comment]
Resolved by #155, closing
