### ISSUE TITLE
Add a drop down list of all available bait sets in the orderportal

### ISSUE THREAD

**Issue by annagellerbring** [Clinical-Genomics/cgweb#159]
- Makes it possible for customers placing orders directly through the orderportal (not via orderform) to see all available bait sets 
- Double checks that orders uploaded through orderforms have a correct bait set specified

To the drop down list, add the option "other (specifiy in comment)" for customers that want to use project specific bait sets that are not available for all customers.

**Comment by patrikgrenfeldt** [comment]
Resolved by #169
