### ISSUE TITLE
Block possibility for FFPE samples to be combined with WGx app tag in orderportal

### ISSUE THREAD

**Issue by annaengstrom** [Clinical-Genomics/cgweb#176]
Some customers have ordered human whole genome sequencing on FFPE samples. We do not want to allow such an order. When the customer orders the WGx app tag, sample source should not be able to do be FFPE.

Add description in orderform that this is not a possible combination?

FYI @vwirta @cesve @annagellerbring

**Comment by annaengstrom** [comment]
Could someone please look into this? @patrikgrenfeldt @elevu

**Comment by elevu** [comment]
looking into it!

**Comment by elevu** [comment]
now in prod
