### ISSUE TITLE
Restrict orderportal not to accept samples are not in consecutive order placement

### ISSUE THREAD

**Issue by annaengstrom** [Clinical-Genomics/cgweb#228]
Problem:
On several occasions customer has ordered samples which are not in consecutive order placement, i.e. A1, B1, C1, D1 etc. which is specified on the website.

Empty positions in the sample plates create major problems during pipetting, latest PROD#241.

Solution:
Restrict orderportal so that it only accepts sample placement in consecutive order placement, i.e. A1, B1, C1, D1 etc.

**Comment by elevu** [comment]
I will start working on this today!

Beside changing this on the order portal, do we need to notify customers about this or change information somewhere else? 
To avoid them preparing plates with sample and then understanding they did wrong when submitting the order.

**Comment by annaengstrom** [comment]
This restriction is already specified on the website, but the customers do not always read all instructions on the website. @elevu

**Comment by elevu** [comment]
in prod
