### ISSUE TITLE
orderportal microbial branch - new UDF in orderform

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/cgweb#37]
There is a new field/UDF that needs to be picked up for microbial orders in the order form. It's called "Other species". This is also a UDF in LIMS that needs to be filled in from the submission. See example OF attached here.
[1603-6_1603-6_Orderform_Microbial_WGS.xlsx](https://github.com/Clinical-Genomics/cgweb/files/1859211/1603-6_1603-6_Orderform_Microbial_WGS.xlsx)

Requirements: The new UDF needs to be selectable in the microbial part of the orderportal and it should be filled in when this field is filled in in the order form. The information also needs to be stored in LIMS on sample level.

Actions:
* [ ] Add the new UDF (concentration) to the orderportal (cgweb/cg)
* [x] Add other_strain text box in the web interface (cgweb)
* [x] Check UDF against excel (cgweb)
* [ ] Document in atlas (?) how to add UDFs to the orderportal (target bioiters)
  * [ ] Doc how to add in excel
  * [ ] Doc how to add in OP/cg
  * [ ] Doc how to add in LIMS

DoD:
For patch except it does not have to be merged to production. The microbial branch has not been validated for production use yet.

**Comment by patrikgrenfeldt** [comment]
- [ ]  Add other_strain textbox
- [ ]  Check UDF against Excel
