### ISSUE TITLE
Update handling of secrets/auth

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/cgweb#5]
This looks promising: https://github.com/nuxt/nuxt.js/issues/1769

Perhaps look at the official guide: https://nuxtjs.org/examples/auth-routes

Persistedstate? https://stackoverflow.com/questions/44126493/i-want-to-use-window-localstorage-in-vuex-in-nuxt-js

**Comment by patrikgrenfeldt** [comment]
@robinandeer what is the problem description of what we want to solve in this issue?

**Comment by patrikgrenfeldt** [comment]
closing
