### ISSUE TITLE
Add a bumpversion?

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/cgweb#62]
As a deployment manager, I would like to see this tool (cgweb) have a version number :)

problem:
there is no bumpversion file and versions cannot be bumped. This leads to not knowing what version is installed in production

suggestion solution:
Add a bumpversion.cfg file. See https://github.com/peritus/bumpversion for more info.

Questions:
Q: as this repo didn't have a bumpversion.cfg file, maybe it was skipped for a reason? Do we need to add the bumpversion?

DoD:
minor

**Comment by patrikgrenfeldt** [comment]
it's there
