### ISSUE TITLE
Have OP check the version of the OF

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/cgweb#63]
As a customer, I want to know for sure that the OF I upload is the latest version.

Problem
Now a customer can use any version of the OF without any problems. The behaviour of the OP is undetermined when one would upload an older version of the OF. See AMS deviation complaintsClinical-Genomics/cgweb#36 for an example.

Steps to reproduce
1. Take OF 1508:8 and fill in tumor 'yes' for any sample
2. upload it to the current OP
3. The tumor field will be marked as 'no' in the OP

Suggested solution
Add a hidden field to the OF denoting the version number. Add check in OP checking that field.

Questions?

DoD:
- close Complaints # 36

**Comment by emiliaol** [comment]
@patrikgrenfeldt Isn't this implemented already?

**Comment by patrikgrenfeldt** [comment]
Jo du kan st=C3=A4nga =C3=A4rendet

Den tis 4 dec. 2018 10:51 skrev emiliaol <notifications@zube.io>:

> [image: Zube logo]
> [image: Event icon]
>
> [image: User avatar] emiliaol *mentioned* you in a comment on a *Card*
>
> [image: Resource icon] #1847 (Clinical-Genomics/cgweb #63) Have OP check
> the version of the OF
> <https://zube.io/clinical-genomics/pbl-team-lessteamnamegreater/c/1847>
>
> @patrikgrenfeldt Isn't this implemented already?
>
> Clinical Genomics/PBL Team <teamname>
>
> You are receiving this notification because you are subscribed to this
> item.
> You can change your notification settings at
> https://zube.io/clinical-genomics/pbl-team-lessteamnamegreater//edit.
>
> Have questions? Get in touch! <support@zube.io>
>
