### ISSUE TITLE
Sanitize organism names for microbial samples

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/cgweb#8]
Standardize the moenclature for organisms when filling in an order.

**Comment by patrikgrenfeldt** [comment]
Could you give some examples?

**Comment by emiliaol** [comment]
@ingkebil @patrikgrenfeldt @sylvinite Is this something we still need to do? And where do we need to clean them up more precisely?

**Comment by patrikgrenfeldt** [comment]
I believe I've done this, strain/species is no called organism

**Comment by emiliaol** [comment]
Awesome!
