### ISSUE TITLE
Add order type cancer to the order portal

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/cgweb#89]
Contact person: Anna G

As a customer support person at CG I want the customers to be able to order prep, sequencing and analysis of cancer panels in the order portal so that I know the order is registered the correct way so that cancer samples are handled in an organized manner through the Order portal. 

Problem description: Orders of our different cancer panels are done using order forms not adapted to this kind of analysis. We often have to come up with a solution to connected problems on the fly. It would be a lot easier if the order portal could handle this instead.

Suggested solution:
1. Make a specific OF for cancer samples. We need a way to separate this form from the clinical samples that have the same Analysis types -> perhaps a hidden key in the form? AG and ES know what needs to be in that (a draft: [Orderform_Cancer_samples.xlsx](https://zube.io/files/clinical-genomics/ff95eaf03a3775109ea3d15b3e765b40-orderform_cancer_samples.xlsx))
* Analysis: Choice for **only** balsamic and **both** balsamic and mip
*Gene panel choice if MIP-analysis?
* paired/single analysis - how to couple samples together?
* identify tumor samples, UDF tumor?

2. Add a new type of order in the portal called "Cancer panels". in cg and cgweb.
 - Might have to rework how the old types are handled since they are dependent on the "Analysis Type" UDF which will be overlapping here.
3. Update the wiki (https://github.com/Clinical-Genomics/orderportal/wiki)
4. Test internally

DoD:
* In production with a first draft of the ordering to meet the needs of the cancer team
* Documented in the wiki

How to demo:
* Show the new OF
* Make a new order in the portal.
* Select the cancer panels order and show what can be filled in. Also tell where the information is stored

Q1: In the problem description there are problems mentioned, which are these problems?
A1: That we often miss information we want to add and that we sometimes have to fill in information that is not relevant.

**Comment by patrikgrenfeldt** [comment]
Prerefined
