### ISSUE TITLE
Update of information on the webpage

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/cgweb#90]
Contact persons: KE och CS

As a customer support responsible I want the information on the clinical genomics web page to be up to date so that I can spend less of my time writing the same information over and over and so that the information is easy for the customers to find.

Problem description: KE and CS will prepare the text and content but they need help updating the web page.

Suggested solution:
~~Either we publish the text or~~ we show them (KE and CS) how to update the content on github and do a pull request + write a manual how to do it. Also add how to deploy (but specify that TTN does that)

DoD:
*published a (very) short guide in AM + training for KE and CS
*passed usability test

How to demo:
* Show the AM guide and the cgweb repo

Q1: what is 'the information'.
A1: like in the cgweb/pages/{requirements.vue, contact.vue, delivery.vue, index.vue, orders.vue, policy.vue}
Q2: How is the information presented? Link, splash page, something else?
A2: text
Q3: Who are 'we'?
A3: TTN
Q4: Does this entail any coding?
A4: No
Q5: Is the DoD S(-pecific)MART enough?
A5: Yes

**Comment by b4ckm4n** [comment]
Pre-refined by BS and DB
